services:
  stremio-http-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stremio-http-proxy
    env_file:
      - .env
    ports:
      - "8691:8691"
    volumes:
      - app-var:/app/var
    depends_on:
      - redis
    restart: unless-stopped

  stremio-http-proxy-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "stremio_http_proxy.cli", "worker"]
    env_file:
      - .env
    volumes:
      - app-var:/app/var
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: stremio-http-proxy-redis
    restart: unless-stopped

volumes:
  app-var:
